### ISSUE TITLE
Form input validation highlighting doesn't match field errors state

### ISSUE THREAD

**Issue by rpocklin** [odecee/angular-form-lib#13]
We are using the form validation **field-errors** directive with the **form-input** directive which works great except for when, after blurring the input with invalid data (field errors and input error highlighting appear) and then changing the input value back into a valid state, the field error messages disappear however the **has-error** and accompanying error classes remain on the field until it is blurred again.

Changing the L.O.C. in `function watchForBlurEvent` from 
```
element.bind('blur', function ngShowWatchAction() {
```
to
```
element.bind('blur keyup', function ngShowWatchAction() {
```

solves the problem but will add overhead.  Thoughts?

**Comment by uglow** [comment]
@rpocklin sorry for the delay. It may need to be more dynamic around which events it listens to because the validation behaviour triggers change over time too (e.g. initially a field does not validate until blur, but then it validates on change once a form-submit attempt has occurred).

**Comment by rpocklin** [comment]
Yeah, this was just an quick change to demo the desired behaviour.

The core of the issue I believe is more around the fact that even **after** submitting, the `form-input` doesn't seem to listen to changes to it's own *ng-model* which can change external to the form input (ie. via other events, cross-dependent fields etc.)

**Comment by uglow** [comment]
@rpocklin Are you able to provide an example of the behaviour you mean? I can understand what you're saying, but I'm not sure of the best way to reproduce the issue.

**Comment by uglow** [comment]
Alright, I think I can easily reproduce this.

**Comment by rpocklin** [comment]
@uglow great that you can reproduce it.  For our use-case, it was more that it wasn't watching for changes to the model (which can happen outside user directly entering data into the field.)  This limits / inhibits rules regarding cross-field validation.  Will it work for this case too?

**Comment by uglow** [comment]
Once an error is showing, when using the default policy, the field starts watching for changes to the error state, not for key up or keydown events. So I think it should work in the case you've described.

Sent from my iPhone

On 2 Aug 2016, at 9:12 AM, Robert Pocklington <notifications@github.com<mailto:notifications@github.com>> wrote:


@uglow<https://github.com/uglow> great that you can reproduce it. For our use-case, it was more that it wasn't watching for changes to the model (which can happen outside user directly entering data into the field.) This limits / inhibits rules regarding cross-field validation. Will it work for this case too?

-

**Comment by uglow** [comment]
V2.1.1 has the changes. Try it out and see if it works as expected.

Sent from my iPhone

On 2 Aug 2016, at 9:12 AM, Robert Pocklington <notifications@github.com<mailto:notifications@github.com>> wrote:


@uglow<https://github.com/uglow> great that you can reproduce it. For our use-case, it was more that it wasn't watching for changes to the model (which can happen outside user directly entering data into the field.) This limits / inhibits rules regarding cross-field validation. Will it work for this case too?

-

**Comment by rpocklin** [comment]
Thanks, will do in the next week or two - we have to move from v1 to v2 :fearful:
