### ISSUE TITLE
Triggering form validation (and scrolling to first error) programatically

### ISSUE THREAD

**Issue by rpocklin** [odecee/angular-form-lib#17]
We have a use case where we need to present the user with a field-level error on a form if a specific API error code is returned, after the `submit` function is called via the `form-submit` directive.

The problem is there seems to be no way to trigger this without repeating the form button submit (ie. clicking it).

Some parts of this codebase suggestion events could be used for this but it appears incomplete or no longer the way it works.

Basically, we want to do the following:
* User clicks the submit button
* `angular-form-validation` passes the form validation
* `submit` function is called (asynchronously calling an API)
* API returns with a specific error code
* a field-level error is added to the form (`form.$valid` is now `false`) but shows no visual error
* re-run `angular-form-lib` state/change code to show the error and scroll to it.

The last step is something we are having trouble with.  Any suggestions @uglow ?

**Comment by uglow** [comment]
Hi @rpocklin, have a look at the Error Message Container example: https://odecee.github.io/angular-form-lib/#/formInput#errorMessageContainer

In the example, if you click the text "Toggle text error", field-level error messages will appear (and disappear if you click again). This mechanism was designed for your use-case: rendering errors that have been returned from an API.

**Comment by rpocklin** [comment]
That function looks like it just toggles the value of a string, so you mean to use `text-errors` attribute rather than add it to `field-errors` for API errors?  Seems annoying to have two mechanisms.  Everything works as expected using `field-errors` except a way to 'trigger' the show / scroll behaviour.  Is the problem that `field-errors` are only checked on explicit model changes?

**Comment by uglow** [comment]
You may be able to fire the `event:FormSubmitAttempted` event against the `<form>` element's `$scope`. E.g.: https://github.com/odecee/angular-form-lib/blob/master/src/modules/ngFormLib/policy/FormPolicy.js#L112

This is what the Form.setSubmitted() method is doing. If that works, you might as well call `form.setSubmitted()` directly which applies some other behaviours.

**Comment by rpocklin** [comment]
Ok, I tried both and calling `form.setSubmitted(true);` does what I'm after.  Many thanks for the help.
