### ISSUE TITLE
Duplicate name in div and input

### ISSUE THREAD

**Issue by philipbeadle** [odecee/angular-form-lib#2]
Using the 0.3.1 version the containing div now has a uid and name attribute and also form-input.  This makes duplicate name attribute which breaks the for on the label and means the name property on the input does not update when the index is changed.

here's the output.
```
<div class="form-group" form-input="" uid="stepName_0" name="stepName_0">
<label class="control-label" for="stepName_0">&nbsp;<span class="required ng-isolate-scope" aria-hidden="true" ng-class="{'ng-hide': hide}" ng-transclude="" required-marker="" hide="!(true)"></span></label>
<div class="control-row"><input type="text" class="form-control ng-pristine ng-invalid ng-invalid-required" id="stepName_0" name="stepName_0" maxlength="250" ng-model="step.name" ng-required="true" aria-required="true" required="required"><span ng-transclude=""></span></div>
</div>
```

**Comment by philipbeadle** [comment]
this is the template line from your code
          template:          '<div class="form-group"><label class="control-label"></label><div class="control-row"><input #type# class="form-control"><span ng-transclude></span></div></div>' 
from common.js

**Comment by uglow** [comment]
Hi Phil,

According to the [unit test](https://github.com/Odecee/angular-form-lib/blob/master/src/modules/ngFormLib/controls/formInput/unitTest/FormInput.spec.js#L23) for form input, there should not be a `name` attribute remaining on the form-input element.

Which version of Angular are you using?

**Comment by uglow** [comment]
This is a screenshot of IE8's DOM of the angular-form-lib website, using Angular 1.2.28 with the latest source code:
<img width="448" alt="screen shot 2015-08-25 at 11 33 02 am" src="https://cloud.githubusercontent.com/assets/3990189/9456596/373beaa8-4b1d-11e5-8355-64c616835b8e.png">

This is the line responsible for removing the uid & name attributes: https://github.com/Odecee/angular-form-lib/blob/master/src/modules/ngFormLib/controls/common/FormControlsService.js#L99
