### ISSUE TITLE
Hi Brett

### ISSUE THREAD

**Issue by leonardoanalista** [odecee/angular-form-lib#5]
Nate wants to have a text hint for a input. Text has two lines. Basically he wants to pass a html or something to achieve that. 
Is is possible to have this 2 lines text hint?

**Comment by uglow** [comment]
Yes, it is possible. There are two ways. There is a `fieldhint` property you can use (see http://odecee.github.io/angular-form-lib/##formInput), or you can use your own HTML for the field and structure it how you wish (there are examples in the above link too).

**Comment by leonardoanalista** [comment]
Thanks Brett, I ll forward to him. I think the html content was getting escaped.

**Comment by diffidentDude** [comment]
Hey Brett, 

I am using the field-hint property, but it is escaping the HTML in the string that I am passing in. Is there any way to avoid this?

**Comment by uglow** [comment]
Hi Nate, as discussed, this can be fixed by using a custom component.
